-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE anlse.tb_pssoa_ (
	cd_pssoa numeric(9) NULL,
	nm_pssoa varchar(200) NULL,
	cd_tpo_pssoa bpchar(1) NULL,
	cd_sexo bpchar(1) NULL,
	dt_nasc_pssoa date NOT NULL,
	cd_pssoa_vnclo numeric(9) NULL,
	ds_bleto text NULL,
	cd_senha bpchar(40) NULL,
	cd_tpo_ctrl numeric(1) NULL,
	nm_fants bpchar(100) NULL,
	cd_tpo_empr numeric(1) NULL,
	cd_tpo_tribt numeric(1) NULL,
	ds_obs text NULL,
	cd_pssoa_agpto numeric NULL,
	cd_condc int4 NULL,
	ds_obs_bleto varchar(150) NULL,
	pc_impst numeric(5, 2) NULL,
	bl_arqvd bool NOT NULL,
	bl_bloq_dados bool NULL,
	bl_susp_pgto bool NULL,
	cd_tpo_estbl int4 NULL,
	nm_pssoa_scial varchar(200) NULL,
	bl_pssoa_grp_gente bool NOT NULL
);